# -*- coding: utf-8 -*-
# Generated by Django 1.11a1 on 2017-09-07 14:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_expensedetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expensedetails',
            name='price',
            field=models.IntegerField(),
        ),
    ]
