# -*- coding: utf-8 -*-
# Generated by Django 1.11a1 on 2017-09-04 21:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='price',
            field=models.IntegerField(blank=True),
        ),
    ]
